### ISSUE TITLE
issue with export android project 

### ISSUE THREAD

**Issue by Al-Asl** [Unity-Technologies/EntityComponentSystemSamples#96]
I'm working on android project which use unity in simple way , when I try to export android project with ecs I get the following exception when unity start : 

> 2019-01-24 13:03:40.778 8957-8986/appName.company.com.companyE/CRASH: pid: 8957, tid: 8986, name: UnityMain  >>> appName.company.com.company<<<
> 2019-01-24 13:03:41.431 8957-8986/appName.company..com.companyE/MessageQueue: IdleHandler threw exception
>     java.lang.Error: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 00000098
>     Build fingerprint: 'google/angler/angler:8.1.0/OPM3.171019.016/4565142:user/release-keys'
>     Revision: '0'
>     pid: 8957, tid: 8986, name: UnityMain  >>> appName.company.com.company<<<
>         r0 00000098  r1 c62de000  r2 00000000  r3 00000098
>         r4 c2659c10  r5 c37c8b00  r6 dead203c  r7 c237d5c8
>         r8 c7bfe698  r9 c37b3c90  sl c7bfe5a0  fp c7bfda0c
>         ip c2659e9c  sp c7bfd9e8  lr c242a43c  pc c242a040  cpsr e52c1c90
>     
>         at libmono.0016a040(Native Method)
>         at libmono.mono_jit_info_table_find(mono_jit_info_table_find:76)
>         at libmono.000e816c(Native Method)
>         at libmono.000e5e18(Native Method)
>         at libmono.000e6028(Native Method)
>         at libmono.000e723c(Native Method)
>         at libmono.000e73ac(Native Method)
>         at libmono.mono_stack_walk(mono_stack_walk:44)
>         at libmono.00241808(Native Method)
>         at libmono.002469f8(Native Method)
>         at libmono.mono_thread_interruption_checkpoint(mono_thread_interruption_checkpoint:12)
>         at Unknown.00002384(Unknown Source:0) 

I know that ecs still in preview but I'm not using anything from unity api, I need the performance gain from the ecs, I'm not using Burst or job system in the project , and I'm using Unity 2018.2.8f1.

**Comment by Al-Asl** [comment]
that error was because I have the habit to replace only the asset folder from the android project ,that's not the case when ECS is imported to the project the whole unity model need to be re-imported.
